### ISSUE TITLE
Digest campaigns are sent even with no new items to tell about

### ISSUE THREAD

**Issue by pstimpel** [hizzle-co/noptin#801] opened 2024-03-20 08:15 UTC
### Description

Hi, After the recent update I found that digest campaigns ("daily") are sent out even if there are now new blog posts to tell about. Wordpress is uptodate, as Noptin is. What changed, and how to switch back to the desired behavior that digest campaigns are only triggering the mail sending if there are any new items to tell about?

**Comment by picocodes** [comment] 2024-03-20 10:25
Duplicate of #792

**Closed** 2024-03-20 10:25 UTC
Labels: bug

**Comment by pstimpel** [comment] 2024-03-25 16:50
and to add, this is what we are using

`[[post_digest style=list]]`
