### ISSUE TITLE
Incorrect layout after WP 6.5.3. update

### ISSUE THREAD

**Issue by tagworxnet** [hizzle-co/noptin#839] opened 2024-05-08 15:03 UTC
### Description

Elementary functions are no longer available, and the look with the familiar links and functions is also defective. It is probably due to the recently released WordPress 6.5.3 and I hope that they will react quickly. Sending newsletters no longer seems to work correctly either. Thx!

### Screenshots

![noptin01](https://github.com/hizzle-co/noptin/assets/122155665/c3f507c9-6c4b-4b11-9a92-ff7f2ed8edf9)
![noptin02](https://github.com/hizzle-co/noptin/assets/122155665/4052da5c-72c0-4e0b-b4b1-049069ef181e)
![noptin03](https://github.com/hizzle-co/noptin/assets/122155665/d74f265b-a6aa-4ba0-9ccf-3e601a249502)

**Comment by picocodes** [comment] 2024-05-31 10:40
Hi @tagworxnet,

I'm not able to reproduce this on our test sites. Check your browser's console for any errors and paste them here.

**Comment by picocodes** [comment] 2024-07-02 05:53
I think this is related to missing German translations. Closing for now.

**Closed by picocodes** 2024-07-02 05:53 UTC
Labels: bug
